version: 2

models:
  - name: stg_jobs
    columns:
      - name: job_id
        tests:
          - not_null

  - name: stg_applications
    columns:
      - name: application_id
        tests:
          - unique
          - not_null

  - name: stg_candidates
    columns:
      - name: candidate_id
        tests:
          - unique
          - not_null